// Mocks generated by Mockito 5.4.6 from annotations
// in mercado_v2/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mercado_v2/app/core/result/result.dart' as _i2;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/entities/auth_user/auth_user.dart'
    as _i6;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/repositories/iauth_repository.dart'
    as _i3;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/usecases/authenticate_usecase.dart'
    as _i7;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/usecases/create_account_usecase.dart'
    as _i8;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/value_objects/value_objects_export.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<S, F> extends _i1.SmartFake implements _i2.Result<S, F> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i3.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> trySignInWithEmailAndPassword(
    _i5.Email? email,
    _i5.Password? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#trySignInWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#trySignInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> trySendPasswordResetEmail(
    _i5.Email? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#trySendPasswordResetEmail, [email]),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#trySendPasswordResetEmail, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> tryCreateUserWithEmailAndPassword(
    _i5.Email? email,
    _i5.Password? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tryCreateUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#tryCreateUserWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);

  @override
  _i4.Future<void> trySendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#trySendEmailVerification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> tryIsEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#tryIsEmailVerified, []),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#tryIsEmailVerified, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> tryGetCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#tryGetCurrentUser, []),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#tryGetCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> tryRefreshCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#tryRefreshCurrentUser, []),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#tryRefreshCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> tryGetRefreshedCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#tryGetRefreshedCurrentUser, []),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#tryGetRefreshedCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> trySignOut() =>
      (super.noSuchMethod(
            Invocation.method(#trySignOut, []),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#trySignOut, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);

  @override
  _i4.Stream<_i6.AuthUser?> onStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#onStateChanges, []),
            returnValue: _i4.Stream<_i6.AuthUser?>.empty(),
          )
          as _i4.Stream<_i6.AuthUser?>);

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> tryUpdateDisplayName(
    _i5.FirstName? firstName,
    _i5.LastName? lastName,
    _i5.SecondLastName? secondLastName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tryUpdateDisplayName, [
              firstName,
              lastName,
              secondLastName,
            ]),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#tryUpdateDisplayName, [
                  firstName,
                  lastName,
                  secondLastName,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);
}

/// A class which mocks [AuthenticationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationUseCase extends _i1.Mock
    implements _i7.AuthenticationUseCase {
  MockAuthenticationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i7.AuthUserStatus> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Stream<_i7.AuthUserStatus>.empty(),
          )
          as _i4.Stream<_i7.AuthUserStatus>);
}

/// A class which mocks [CreateAccountUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateAccountUsecase extends _i1.Mock
    implements _i8.CreateAccountUsecase {
  MockCreateAccountUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<dynamic, dynamic>> call({
    required String? emailString,
    required String? passwordString,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #emailString: emailString,
              #passwordString: passwordString,
            }),
            returnValue: _i4.Future<_i2.Result<dynamic, dynamic>>.value(
              _FakeResult_0<dynamic, dynamic>(
                this,
                Invocation.method(#call, [], {
                  #emailString: emailString,
                  #passwordString: passwordString,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<dynamic, dynamic>>);
}
