// Mocks generated by Mockito 5.4.6 from annotations
// in mercado_v2/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mercado_v2/app/core/result/result.dart' as _i4;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/entities/auth_user/auth_user.dart'
    as _i7;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/repositories/i_auth_repository.dart'
    as _i2;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/usecases/authenticate_usecase.dart'
    as _i8;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/usecases/create_account_usecase.dart'
    as _i9;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/usecases/login_usecase.dart'
    as _i10;
import 'package:mercado_v2/features/auth/email_fb_authentication/domain/value_objects/value_objects_export.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i2.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void, _i4.AuthFailure>> trySignInWithEmailAndPassword(
    _i5.Email? email,
    _i5.Password? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#trySignInWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i3.Future<_i4.Result<void, _i4.AuthFailure>>.value(
              _i6.dummyValue<_i4.Result<void, _i4.AuthFailure>>(
                this,
                Invocation.method(#trySignInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i4.AuthFailure>>);

  @override
  _i3.Future<_i4.Result<void, _i4.AuthFailure>>
  tryCreateUserWithEmailAndPassword(_i5.Email? email, _i5.Password? password) =>
      (super.noSuchMethod(
            Invocation.method(#tryCreateUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i3.Future<_i4.Result<void, _i4.AuthFailure>>.value(
              _i6.dummyValue<_i4.Result<void, _i4.AuthFailure>>(
                this,
                Invocation.method(#tryCreateUserWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i4.AuthFailure>>);

  @override
  _i3.Future<_i4.Result<void, _i4.AuthFailure>> trySendVerificationEmail() =>
      (super.noSuchMethod(
            Invocation.method(#trySendVerificationEmail, []),
            returnValue: _i3.Future<_i4.Result<void, _i4.AuthFailure>>.value(
              _i6.dummyValue<_i4.Result<void, _i4.AuthFailure>>(
                this,
                Invocation.method(#trySendVerificationEmail, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i4.AuthFailure>>);

  @override
  _i3.Future<_i4.Result<bool, _i4.AuthFailure>> tryIsEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#tryIsEmailVerified, []),
            returnValue: _i3.Future<_i4.Result<bool, _i4.AuthFailure>>.value(
              _i6.dummyValue<_i4.Result<bool, _i4.AuthFailure>>(
                this,
                Invocation.method(#tryIsEmailVerified, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool, _i4.AuthFailure>>);

  @override
  _i3.Stream<_i7.AuthUser?> onStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#onStateChanges, []),
            returnValue: _i3.Stream<_i7.AuthUser?>.empty(),
          )
          as _i3.Stream<_i7.AuthUser?>);
}

/// A class which mocks [AuthenticationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationUseCase extends _i1.Mock
    implements _i8.AuthenticationUseCase {
  MockAuthenticationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i8.AuthUserStatus> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Stream<_i8.AuthUserStatus>.empty(),
          )
          as _i3.Stream<_i8.AuthUserStatus>);
}

/// A class which mocks [CreateAccountUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateAccountUsecase extends _i1.Mock
    implements _i9.CreateAccountUsecase {
  MockCreateAccountUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void, _i4.AuthFailure>> call({
    required String? emailString,
    required String? passwordString,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #emailString: emailString,
              #passwordString: passwordString,
            }),
            returnValue: _i3.Future<_i4.Result<void, _i4.AuthFailure>>.value(
              _i6.dummyValue<_i4.Result<void, _i4.AuthFailure>>(
                this,
                Invocation.method(#call, [], {
                  #emailString: emailString,
                  #passwordString: passwordString,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i4.AuthFailure>>);
}

/// A class which mocks [LoginUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUsecase extends _i1.Mock implements _i10.LoginUsecase {
  MockLoginUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void, _i4.AuthFailure>> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i4.Result<void, _i4.AuthFailure>>.value(
              _i6.dummyValue<_i4.Result<void, _i4.AuthFailure>>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i4.AuthFailure>>);
}
