// Mocks generated by Mockito 5.4.6 from annotations
// in mercado_v2/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mercado_v2/app/core/result/result.dart' as _i2;
import 'package:mercado_v2/features/auth/new_fb_authentication/domain/entities/auth_user/new_auth_user.dart'
    as _i5;
import 'package:mercado_v2/features/auth/new_fb_authentication/domain/repositories/newiauth_repository.dart'
    as _i3;
import 'package:mercado_v2/features/auth/new_fb_authentication/domain/value_objects/newvalue_objects_export.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NewIAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewIAuthRepository extends _i1.Mock
    implements _i3.NewIAuthRepository {
  MockNewIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.NewAuthUser>> trySignInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#trySignInWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i4.Future<_i2.Result<_i5.NewAuthUser>>.value(
              _FakeResult_0<_i5.NewAuthUser>(
                this,
                Invocation.method(#trySignInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.NewAuthUser>>);

  @override
  _i4.Future<_i2.Result<void>> trySendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#trySendPasswordResetEmail, [email]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#trySendPasswordResetEmail, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> tryCreateUserWithEmailAndPassword(
    _i6.NewEmail? email,
    _i6.NewPassword? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tryCreateUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#tryCreateUserWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<void> trySendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#trySendEmailVerification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Result<bool>> tryIsEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#tryIsEmailVerified, []),
            returnValue: _i4.Future<_i2.Result<bool>>.value(
              _FakeResult_0<bool>(
                this,
                Invocation.method(#tryIsEmailVerified, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<bool>>);

  @override
  _i4.Future<_i2.Result<_i5.NewAuthUser?>> tryGetCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#tryGetCurrentUser, []),
            returnValue: _i4.Future<_i2.Result<_i5.NewAuthUser?>>.value(
              _FakeResult_0<_i5.NewAuthUser?>(
                this,
                Invocation.method(#tryGetCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.NewAuthUser?>>);

  @override
  _i4.Future<_i2.Result<void>> tryRefreshCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#tryRefreshCurrentUser, []),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#tryRefreshCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<_i5.NewAuthUser?>> tryGetRefreshedCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#tryGetRefreshedCurrentUser, []),
            returnValue: _i4.Future<_i2.Result<_i5.NewAuthUser?>>.value(
              _FakeResult_0<_i5.NewAuthUser?>(
                this,
                Invocation.method(#tryGetRefreshedCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.NewAuthUser?>>);

  @override
  _i4.Future<_i2.Result<void>> trySignOut() =>
      (super.noSuchMethod(
            Invocation.method(#trySignOut, []),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#trySignOut, [])),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<_i5.NewAuthUser?> onStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#onStateChanges, []),
            returnValue: _i4.Stream<_i5.NewAuthUser?>.empty(),
          )
          as _i4.Stream<_i5.NewAuthUser?>);

  @override
  _i4.Future<_i2.Result<void>> tryUpdateDisplayName(
    String? firstName,
    String? lastName,
    String? secondLastName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tryUpdateDisplayName, [
              firstName,
              lastName,
              secondLastName,
            ]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#tryUpdateDisplayName, [
                  firstName,
                  lastName,
                  secondLastName,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);
}
